---
deployment:
  tasks:
    - cd /home1/anthon99/project/ && git pull origin production
    - export DEPLOYPATH=/home1/anthon99/projectapi.meusite.com/
    - mkdir -p $DEPLOYPATH/backend
    - mkdir -p $DEPLOYPATH/frontend
    - /bin/cp -R backend/* $DEPLOYPATH/backend/
    - /bin/cp -R frontend/build/* $DEPLOYPATH/frontend/
