version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
