name: Fullstack CI

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  backend-tests:
    name: Laravel Testes
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências Laravel
        run: |
          cd backend
          cp .env.example .env
          composer install
          php artisan key:generate
          php artisan migrate --force

      - name: Rodar testes Laravel (somente Feature)
        run: cd backend && php artisan test tests/Feature
 

  frontend-tests:
    name: React Testes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências React
        run: cd frontend && npm install

      - name: Rodar testes React
        run: cd frontend && npm test -- --watchAll=false
