name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Instalar dependências React
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Instalar dependências Laravel
        working-directory: backend
        run: |
          cp .env.example .env
          composer install --no-dev --optimize-autoloader
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan storage:link

      - name: Merge main → production
        run: |
          git checkout production || git checkout -b production
          git merge origin/main --no-edit
          git add -f frontend/build/ || true
          git add -f backend/vendor/ || true
          git add -f backend/bootstrap/cache/ || true
          git commit -m "build: versão gerada automaticamente pelo deploy.yml" || echo "Nenhum commit necessário"
          git push origin production
