name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Instalar dependências React
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Instalar dependências Laravel
        working-directory: backend
        run: |
          cp .env.example .env
          composer install --no-dev --optimize-autoloader
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan storage:link

      - name: Commitar alterações locais (build e cache)
        run: |
          git add -f frontend/build/
          git add -f backend/vendor/
          git add -f backend/bootstrap/cache/
          git commit -m "build: atualiza build e cache antes do deploy" || echo "Nenhum commit necessário"

      - name: Checkout production e merge main → production
        run: |
          git fetch origin
          git checkout production || git checkout -b production origin/production
          git merge origin/main --no-edit

      - name: Puxar atualizações da production (caso existam)
        run: |
          git pull origin production --allow-unrelated-histories || true

      - name: Push para production
        run: |
          git push origin production
